"""Rust acceleration for WSE. Rust is mandatory -- crashes if not built."""

from wse_server._wse_accel import (
    RustCompressionManager,
    RustEventSequencer,
    RustPriorityMessageQueue,
    RustPriorityQueue,
    RustSequencer,
    RustTokenBucket,
    RustWSEServer,
    rust_aes_gcm_decrypt,
    rust_aes_gcm_encrypt,
    rust_compress,
    rust_decompress,
    rust_ecdh_derive_shared_secret,
    rust_ecdh_generate_keypair,
    rust_hmac_sha256,
    rust_jwt_decode,
    rust_jwt_encode,
    rust_match_event,
    rust_sha256,
    rust_should_compress,
    rust_sign_message,
    rust_transform_event,
)

__all__ = [
    "RustCompressionManager",
    "RustEventSequencer",
    "RustPriorityMessageQueue",
    "RustPriorityQueue",
    "RustSequencer",
    "RustTokenBucket",
    "RustWSEServer",
    "rust_aes_gcm_decrypt",
    "rust_aes_gcm_encrypt",
    "rust_compress",
    "rust_decompress",
    "rust_ecdh_derive_shared_secret",
    "rust_ecdh_generate_keypair",
    "rust_hmac_sha256",
    "rust_jwt_decode",
    "rust_jwt_encode",
    "rust_match_event",
    "rust_sha256",
    "rust_should_compress",
    "rust_sign_message",
    "rust_transform_event",
]
